from setuptools import setup, find_packages

setup(
    name="go2_mpc",
    version="0.1.0",
    description="Model Predictive Control for Go1 Quadruped Robot",
    author="Generated by Gemini",
    packages=find_packages(),
    install_requires=[
        "mujoco>=2.3.0",
        "numpy",
        "pinocchio",
        "cvxpy",
        "scipy",
    ],
    python_requires=">=3.7",
)